server:
  port: 8071
spring:
  application:
    name: tb-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guoyujun3699/config-1911.git
          search-paths: / #ÅäÖÃÎÄ¼şÂ·¾¶
          username:
          password:
          skip-ssl-validation: true
      label: master
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
